# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Octoplex < Formula
  desc "Octoplex is a live video restreamer for the terminal."
  homepage "https://github.com/rfwatson/octoplex"
  version "0.0.0-feature-test"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rfwatson/octoplex/releases/download/v0.0.0-feature-test/octoplex_Darwin_x86_64.tar.gz"
      sha256 "67dfbc356d83b37ca831d5031809cb68b9b45ef12486df8b2541c953dc59e4b5"

      def install
        bin.install "octoplex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rfwatson/octoplex/releases/download/v0.0.0-feature-test/octoplex_Darwin_arm64.tar.gz"
      sha256 "1e6dd1dc0ef0b1f93de49f435c6f93f2656cd873d3d92e5014ac430eec2ceea3"

      def install
        bin.install "octoplex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rfwatson/octoplex/releases/download/v0.0.0-feature-test/octoplex_Linux_x86_64.tar.gz"
        sha256 "e35506ff0e1b8f0eb1b1def9d55214f4d6094af612581fa0d5b7dfeaaca530d3"

        def install
          bin.install "octoplex"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rfwatson/octoplex/releases/download/v0.0.0-feature-test/octoplex_Linux_arm64.tar.gz"
        sha256 "8c88698853b60d82c860b2bd9a2954cef2c080afdb9ae7540ee4ac019d2d7e57"

        def install
          bin.install "octoplex"
        end
      end
    end
  end

  test do
    system "#{bin}/octoplex -h"
  end
end
