# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Octoplex < Formula
  desc "Octoplex is a live video restreamer for the terminal."
  homepage "https://github.com/rfwatson/octoplex"
  version "0.0.8-beta.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rfwatson/octoplex/releases/download/v0.0.8-beta.9/octoplex_Darwin_x86_64.tar.gz"
      sha256 "2d2f4f6889caf2f2c59f435a61f3b75867ffed00c0f2d44e030fba94450eb320"

      def install
        bin.install "octoplex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rfwatson/octoplex/releases/download/v0.0.8-beta.9/octoplex_Darwin_arm64.tar.gz"
      sha256 "0eae9692986683a5a5f4102063ad9745e871d47ca7fc5acb3bad83c9cf677358"

      def install
        bin.install "octoplex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rfwatson/octoplex/releases/download/v0.0.8-beta.9/octoplex_Linux_x86_64.tar.gz"
        sha256 "a989c15e7be159df7d4412b75008b0b8dd7ad0da97254bddbcbc022bdf4c7030"

        def install
          bin.install "octoplex"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rfwatson/octoplex/releases/download/v0.0.8-beta.9/octoplex_Linux_arm64.tar.gz"
        sha256 "ae373ee3e47c3edd9b79bb2a1c85226d3390b7ed78eede3ec19214df49acc967"

        def install
          bin.install "octoplex"
        end
      end
    end
  end

  test do
    system "#{bin}/octoplex -h"
  end
end
